manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/weteor/zmk/tree/013d2fce8cf6c66d7fa3ada58e2a0cb53e76c25f
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 013d2f
      import: app/west.yml
  self:
    path: config
